app:
  locale: ${LOCALE:en}

pagination:
  max-page-size: ${MAX-PAGE-SIZE:100}

server:
  port: ${SERVER_PORT:8080}
  tomcat:
    max-keep-alive-requests: ${TOMCAT_MAX-KEEP-ALIVE-REQUESTS:100}
    accept-count: ${TOMCAT_ACCEPT_COUNT:100}
    max-connections: ${TOMCAT_MAX_CONNECTIONS:8192}
    threads:
      max: ${TOMCAT_MAX_THREADS:200}
      min-spare: ${TOMCAT_MIN_THREADS:10}

spring:
  config.import: optional:classpath:secret/secret.properties
  application.name: ewallet
  transaction.default-timeout: ${TRANSACTION_TIMEOUT:1}
  devtools.restart.enabled: false

  jpa:
    hibernate.ddl-auto: none
    open-in-view: false
    show-sql: false
    properties.hibernate.format_sql: true
    database: postgresql

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${DB_POOL_MAX_SIZE:100}
      minimum-idle: ${DB_POOL_MIN_IDLE:5}
      connection-timeout: ${DB_CONNECTION_TIMEOUT:1000}
      idle-timeout: ${DB_IDLE_TIMEOUT:30000}
      max-lifetime: ${DB_MAX_LIFETIME:300000}

rate-limiter:
  capacity: ${RATE_LIMIT_CAPACITY:1000}
  refill-tokens: ${RATE_LIMIT_REFILL_TOKENS:1000}
  refill-duration: ${RATE_LIMIT_REFILL_DURATION:1s}
  cache-expire: ${RATE_LIMIT_CACHE_EXPIRE:1m}
  cache-max-size: ${RATE_LIMIT_CACHE_MAX_SIZE:10000}

management:
  endpoint.health.probes.enabled: true
  endpoints.web.exposure.include: health, metrics
  metrics.enable.hikari: true